/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2017-08-09 16:03:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tspd;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tspdssolveHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar", Long.valueOf(1423481836151L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1386784424000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fenctype_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fstyle_005fpath_005fname_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fpath_005fname_005fid_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fenctype_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fstyle_005fpath_005fname_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fpath_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fenctype_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fstyle_005fpath_005fname_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fpath_005fname_005fid_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<h1 class=\"page-header\">TSPD</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<div id=\"googleMap\" style=\"width:100%;height:100%\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_form_005fform_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAruL-HLFSNh6G2MLhjS-eBTea7r7EFa5A&libraries=places&callback=initialize\" async defer></script>\r\n");
      out.write("<script>\r\n");
      out.write("var map;\r\n");
      out.write("var listMarker = [];\r\n");
      out.write("function initialize(){\r\n");
      out.write("\tvar mapProp = {\r\n");
      out.write("\t\tcenter: {lat: 21.033333, lng: 105.849998},\r\n");
      out.write("\t\tzoom: 12,\r\n");
      out.write("\t\tmapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tmap=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("\t\r\n");
      out.write("\tmap.addListener('click',function(event){\r\n");
      out.write("\t\tvar pos = event.latLng;\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar markerPoint = new google.maps.Marker({\r\n");
      out.write("\t\t\tmap: map,\r\n");
      out.write("\t\t\tposition: pos,\r\n");
      out.write("\t\t\tdraggable: true,\r\n");
      out.write("\t\t\ticon: \"https://www.google.com/mapfiles/marker_green.png\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlistMarker.push(markerPoint);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmarkerPoint.addListener('click',function(){\r\n");
      out.write("\t\t\tthis.setMap(null);\r\n");
      out.write("\t\t\tvar indexMarker = listMarker.indexOf(this);\r\n");
      out.write("\t\t\tlistMarker.splice(indexMarker,1);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function run_algorithm(){\r\n");
      out.write("\tvar listPoints = [];\r\n");
      out.write("\tfor(var i=0; i<listMarker.length; i++){\r\n");
      out.write("\t\tlistPoints.push({\r\n");
      out.write("\t\t\t\"ID\" : i,\r\n");
      out.write("\t\t\t\"lat\" : listMarker[i].getPosition().lat(),\r\n");
      out.write("\t\t\t\"lng\" : listMarker[i].getPosition().lng()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#listPoints').val(JSON.stringify(listPoints));\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function save_file(el){\r\n");
      out.write("\tvar listPoints = [];\r\n");
      out.write("\tfor(var i=0; i<listMarker.length; i++){\r\n");
      out.write("\t\tlistPoints.push({\r\n");
      out.write("\t\t\t\"ID\" : i,\r\n");
      out.write("\t\t\t\"lat\" : listMarker[i].getPosition().lat(),\r\n");
      out.write("\t\t\t\"lng\" : listMarker[i].getPosition().lng()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar save_data = {\r\n");
      out.write("\t\t\t\"truckSpeed\" : $('#truckSpeed').val(),\r\n");
      out.write("\t\t\t\"droneSpeed\" : $('#droneSpeed').val(),\r\n");
      out.write("\t\t\t\"truckCost\" : $('#truckCost').val(),\r\n");
      out.write("\t\t\t\"droneCost\" : $('#droneCost').val(),\r\n");
      out.write("\t\t\t\"delta\" : $('#delta').val(),\r\n");
      out.write("\t\t\t\"endurance\" : $('#endurance').val(),\r\n");
      out.write("\t\t\t\"listPoints\" : listPoints\r\n");
      out.write("\t}\r\n");
      out.write("\t//console.log(\"save_data = \"+save_data);\r\n");
      out.write("\t//download(JSON.stringify(save_data),'dataTSP.json','text/plain');\r\n");
      out.write("\tsave_data = \"text/json;charset=utf-8,\" + encodeURIComponent(JSON.stringify(save_data));\r\n");
      out.write("    // what to return in order to show download window?\r\n");
      out.write("\r\n");
      out.write("    el.setAttribute(\"href\", \"data:\"+save_data);\r\n");
      out.write("    el.setAttribute(\"download\", \"dataTSP.json\");\r\n");
      out.write("\twindow.location = baseUrl + \"/tsp-drone/tspds-solve-home\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function upload_file(){\r\n");
      out.write("\t$('#file-tsp-data').click();\r\n");
      out.write("}\r\n");
      out.write("function uploadSolution(){\r\n");
      out.write("\t$('#input-solution').click();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("(function(){\r\n");
      out.write("    \r\n");
      out.write("    function onChange(event) {\r\n");
      out.write("        var reader = new FileReader();\r\n");
      out.write("        reader.onload = onReaderLoad;\r\n");
      out.write("        reader.readAsText(event.target.files[0]);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function onReaderLoad(event){\r\n");
      out.write("        //console.log(event.target.result);\r\n");
      out.write("        var obj = JSON.parse(event.target.result);\r\n");
      out.write("        show_data(obj);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function show_data(obj){\r\n");
      out.write("        //alert('truckSpeed : ' + truckSpeed + ', droneSpeed : ' + droneSpeed);\r\n");
      out.write("    \tlistMarker = [];\r\n");
      out.write("    \tinitialize();\r\n");
      out.write("        $('#truckSpeed').val(obj.truckSpeed);\r\n");
      out.write("    \t$('#droneSpeed').val(obj.droneSpeed);\r\n");
      out.write("    \t$('#truckCost').val(obj.truckCost);\r\n");
      out.write("    \t$('#droneCost').val(obj.droneCost);\r\n");
      out.write("    \t$('#delta').val(obj.delta);\r\n");
      out.write("    \t$('#endurance').val(obj.endurance);\r\n");
      out.write("    \t\r\n");
      out.write("    \tfor(var i=0; i<obj.listPoints.length; i++){\r\n");
      out.write("    \t\tvar point = obj.listPoints[i];\r\n");
      out.write("    \t\tvar pos = new google.maps.LatLng(point.lat, point.lng);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tvar markerPoint = new google.maps.Marker({\r\n");
      out.write("    \t\t\tmap: map,\r\n");
      out.write("    \t\t\tposition: pos,\r\n");
      out.write("    \t\t\tdraggable: true,\r\n");
      out.write("    \t\t\ticon: \"https://www.google.com/mapfiles/marker_green.png\"\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tlistMarker.push(markerPoint);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tmarkerPoint.addListener('click',function(){\r\n");
      out.write("    \t\t\tthis.setMap(null);\r\n");
      out.write("    \t\t\tvar indexMarker = listMarker.indexOf(this);\r\n");
      out.write("    \t\t\tlistMarker.splice(indexMarker,1);\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    document.getElementById('file-tsp-data').addEventListener('change', onChange);\r\n");
      out.write("\r\n");
      out.write("}());\r\n");
      out.write("(function(){\r\n");
      out.write("    \r\n");
      out.write("    function onChange(event) {\r\n");
      out.write("    \tconsole.log(\"input-solution\");\r\n");
      out.write("        $(\"#tspdsolution\").submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    document.getElementById('input-solution').addEventListener('change', onChange);\r\n");
      out.write("\r\n");
      out.write("}());\r\n");
      out.write("/*\r\n");
      out.write("function tspd_solve(){\r\n");
      out.write("\t//console.log(\"-----------\")\r\n");
      out.write("\tvar data = {\r\n");
      out.write("\t\t\"truckSpeed\" : $('#truckSpeed').val(),\r\n");
      out.write("\t\t\"droneSpeed\" : $('#droneSpeed').val(),\r\n");
      out.write("\t\t\"truckCost\" : $('#truckCost').val(),\r\n");
      out.write("\t\t\"droneCost\" : $('#droneCost').val(),\r\n");
      out.write("\t\t\"delta\" : $('#delta').val(),\r\n");
      out.write("\t\t\"endurance\" : $('#endurance').val()\r\n");
      out.write("\t}\r\n");
      out.write("\tdata[\"listPoints\"] = [];\r\n");
      out.write("\tfor(var i=0; i<listMarker.length; i++){\r\n");
      out.write("\t\tdata.listPoints.push({\r\n");
      out.write("\t\t\t\"ID\" : i,\r\n");
      out.write("\t\t\t\"lat\" : listMarker[i].getPosition().lat(),\r\n");
      out.write("\t\t\t\"lng\" : listMarker[i].getPosition().lng()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tconsole.log(\"data send: \"+JSON.stringify(data));\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : 'POST',\r\n");
      out.write("\t\turl : baseUrl + '/tsp-drone/tspd-solve',\r\n");
      out.write("\t\tdata : JSON.stringify(data),\r\n");
      out.write("\t\tcontentType : 'application/json',\r\n");
      out.write("\t});\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fenctype_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}/tsp-drone/uploadSolutionkDrone", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("POST");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setId("tspdsolution");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setCommandName("tspdsolution");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setEnctype("multipart/form-data");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "role", "form");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(12,2) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t<a class=\"btn btn-primary \" id=\"submit-button-solution\" onclick=\"uploadSolution()\" >Upload Solution</a>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fenctype_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fstyle_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setId("input-solution");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("tspdSolutionFile");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "name", "tspdSolutionFile");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "file");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "file file-loading ");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(13,3) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "style", "display:none");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fstyle_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f1 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f1.setParent(null);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(19,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f1.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}/tsp-drone/tspds-solve", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(19,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f1.setMethod("POST");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(19,2) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f1.setCommandName("tspd");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(19,2) null
    _jspx_th_form_005fform_005f1.setDynamicAttribute(null, "role", "form");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(19,2) null
    _jspx_th_form_005fform_005f1.setDynamicAttribute(null, "class", "form-horizontal");
    int[] _jspx_push_body_count_form_005fform_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f1 = _jspx_th_form_005fform_005f1.doStartTag();
      if (_jspx_eval_form_005fform_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div class=\"panel panel-default\">\r\n");
          out.write("\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Truck speed (km/h)</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Drone speed (km/h)</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"row\" style=\"margin-top:10px\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Cost per unit (km) of truck</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Cost per unit (km) of drone</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"row\" style=\"margin-top:10px\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Wait time (Delta) (minute)</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f5(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-3\">Drone endurance (e) (km)</label>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f6(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"row\" style=\"margin-top:10px\">\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f7(_jspx_th_form_005fform_005f1, _jspx_page_context, _jspx_push_body_count_form_005fform_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t<button class=\"btn btn-primary col-lg-offset-5\" onclick=\"run_algorithm();\" type=\"submit\">Run</button>\r\n");
          out.write("\t\t\t\t\t<a class=\"btn btn-primary\" onclick=\"save_file(this);\">Save</a>\r\n");
          out.write("\t\t\t\t\t<a class=\"btn btn-primary\" onclick=\"upload_file();\">Upload</a>\r\n");
          out.write("\t\t\t\t\t<input id=\"file-tsp-data\" class=\"file file-loading\" type=\"file\" style=\"display:none\"/>\t\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\t\t\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(26,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("truckSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(26,7) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "name", "truckSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(26,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setId("truckSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(26,7) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(26,7) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "placeholder", "Truck speed");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(30,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setPath("droneSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(30,7) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "name", "droneSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(30,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setId("droneSpeed");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(30,7) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(30,7) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "placeholder", "Drone speed");
    int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
      if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(38,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setPath("truckCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(38,7) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "name", "truckCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(38,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setId("truckCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(38,7) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(38,7) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "placeholder", "Cost per unit of truck");
    int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
      if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(42,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setPath("droneCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(42,7) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "name", "droneCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(42,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setId("droneCost");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(42,7) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(42,7) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "placeholder", "Cost per unit of drone");
    int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
      if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f4.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f5.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(50,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setPath("delta");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(50,7) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "name", "delta");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(50,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setId("delta");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(50,7) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(50,7) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "placeholder", "Wait time");
    int[] _jspx_push_body_count_form_005finput_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f5 = _jspx_th_form_005finput_005f5.doStartTag();
      if (_jspx_th_form_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f5.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f6.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(54,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f6.setPath("endurance");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(54,7) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "name", "endurance");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(54,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f6.setId("endurance");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(54,7) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(54,7) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "placeholder", "endurance");
    int[] _jspx_push_body_count_form_005finput_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f6 = _jspx_th_form_005finput_005f6.doStartTag();
      if (_jspx_th_form_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f6.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fpath_005fname_005fid_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f7.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f1);
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(59,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f7.setPath("listPoints");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(59,5) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "name", "listPoints");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(59,5) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f7.setId("listPoints");
    // /WEB-INF/views/tspd/tspdssolveHome.jsp(59,5) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "type", "hidden");
    int[] _jspx_push_body_count_form_005finput_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f7 = _jspx_th_form_005finput_005f7.doStartTag();
      if (_jspx_th_form_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f7.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fpath_005fname_005fid_005fnobody.reuse(_jspx_th_form_005finput_005f7);
    }
    return false;
  }
}
