/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2017-08-09 16:04:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.outgoingarticles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewAutoRoute_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar", Long.valueOf(1423481836151L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1386784424000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1423481802197L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables CSS -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables Responsive CSS -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<h1 class=\"page-header\">Xem kế hoạch vận chuyển</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<select class=\"form-control\" id=\"select-listBatch\">\r\n");
      out.write("\t\t\t\t\t<option>Chọn batch</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div id=\"googleMap\" style=\"width:100%; height:100%\"></div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t<div class = \"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" id=\"sel-shipper\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Chọn shipper</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" onclick=\"assignShipper()\" >Assign Shipper</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" onclick=\"viewRoute()\">View Routes</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"dataTable_wrapper\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover\" id=\"tbl-infoOfRoutes\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Mã KH</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Địa chỉ KH</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Thời gian giao hàng dự kiến</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Thời gian giao hàng yêu cầu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Số thứ tự</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Shipper</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Check</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAruL-HLFSNh6G2MLhjS-eBTea7r7EFa5A&libraries=places&callback=initialize\" async defer></script>\r\n");
      out.write("<!-- DataTables JavaScript -->\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var data;\r\n");
      out.write("var checkedList=[];\r\n");
      out.write("var table;\r\n");
      out.write("//var colorInit=[\"#F7786B\",\"#91A8D0\",\"#91A8D0\",\"#034F84\",\"#FAE03C\",\"#98DDDE\",\"#9896A4\",\"#DD4132\",\"#B18F6A\",\"#79C753\",\"#B93A32\",\"#AD5D5D\",\"#006E51\",\"#B76BA3\",\"#5C7148\",\"#D13076\"];\r\n");
      out.write("var colorInit=[\"#B0171F\",\"#FF1493\",\"#8B5F65\",\"#000080\",\"#006400\",\"#a52a2a\",\"#ff0000\",\"#ff1493\",\"#9400d3\"];\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\ttable = $(\"#tbl-infoOfRoutes\").DataTable({\r\n");
      out.write("\t\t\"bSort\" : false\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#select-listBatch').change(function(){\r\n");
      out.write("\t\tvar batchSelected = $(this).val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\turl: baseUrl + \"/outgoingarticles/viewAssignedBatchRoute\",\r\n");
      out.write("\t\t\tdata: batchSelected,\r\n");
      out.write("\t\t\tcontentType: 'application/text',\r\n");
      out.write("\t\t\tsuccess: displayInfo\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var map;\r\n");
      out.write("function initialize() {\r\n");
      out.write("\t//construct google map\r\n");
      out.write("\tvar mapProp = {\r\n");
      out.write("\t\tcenter: {lat: 21.033333, lng: 105.849998},\r\n");
      out.write("\t\tzoom: 12,\r\n");
      out.write("\t\tmapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t};\r\n");
      out.write("\tmap=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("}\r\n");
      out.write("function updateCheckList(i,element){\r\n");
      out.write("\tif(element.checked){\r\n");
      out.write("\t\tconsole.log(\"check[\"+i+\"] checked\");\r\n");
      out.write("\t\tvar tmp= checkedList.indexOf(i);\r\n");
      out.write("\t\tif (tmp == -1) checkedList.push(i);\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tconsole.log(\"check[\"+i+\"] unchecked\");\r\n");
      out.write("\t\tvar tmp= checkedList.indexOf(i);\r\n");
      out.write("\t\tif (tmp != -1) checkedList.splice(tmp,1);\r\n");
      out.write("\t\t//else checkedList.splice(tmp,1);\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function assignShipper(){\r\n");
      out.write("\tvar shipper= $(\"#sel-shipper\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tvar res={\r\n");
      out.write("\t\t\"shipper\":shipper\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t//console.log(shipper);\r\n");
      out.write("\tres.listRoute=[];\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t\tres.listRoute.push(data[checkedList[i]].routeCode);\r\n");
      out.write("\t}\r\n");
      out.write("\tconsole.log(\"data send upadate route:\"+JSON.stringify(res));\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t    type:\"POST\", \r\n");
      out.write("\t    url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ship/update-route-assignshipper\",\r\n");
      out.write("\t    data: JSON.stringify(res),\r\n");
      out.write("\t    contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t    dataType: \"json\",\r\n");
      out.write("\t    success: function(response){\r\n");
      out.write("\t        // Success Message Handler\r\n");
      out.write("\t        //console.log(response);\r\n");
      out.write("\t      \tif(response==true){\r\n");
      out.write("\t      \t\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t      \t\t\t\tdata[checkedList[i]].shipperCode=shipper;\r\n");
      out.write("\t      \t\t}\r\n");
      out.write("\t      \t\tdisplayInfo(data);\r\n");
      out.write("\t      \t\tcheckedList = [];\r\n");
      out.write("\t      \t}\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function viewRoute(){\r\n");
      out.write("\tconsole.log(\"checked list: \"+checkedList);\r\n");
      out.write("\tinitialize();\r\n");
      out.write("\tvar storePosition = data[0].storeLatLng;\r\n");
      out.write("\t//console.log(\"storePostion: \"+storePosition);\r\n");
      out.write("\tvar indexPo = storePosition.indexOf(\",\");\r\n");
      out.write("\tvar storePositionLat = storePosition.substring(0,indexPo);\r\n");
      out.write("\t//console.log(\"storePositionLat: \"+storePositionLat);\r\n");
      out.write("\tvar storePositionLng = storePosition.substring(indexPo+1,storePosition.length);\r\n");
      out.write("\t//console.log(\"storePositionLng: \"+storePositionLng);\r\n");
      out.write("\tvar storePos = new google.maps.LatLng(storePositionLat,storePositionLng);\r\n");
      out.write("\tvar markerStorePostion = new google.maps.Marker({\r\n");
      out.write("\t\tposition: storePos,\r\n");
      out.write("\t\ticon : baseUrl+\"/assets/icon/store-icon.png\",\r\n");
      out.write("\t\tmap: map\r\n");
      out.write("\t});\r\n");
      out.write("\tvar lstinfowindow = [];\r\n");
      out.write("\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t\t//console.log(JSON.stringify(response[i]));\t\t\r\n");
      out.write("\t\tvar route;\r\n");
      out.write("\t\tif(i>=colorInit.length){\r\n");
      out.write("\t\t\troute = new google.maps.Polyline({\r\n");
      out.write("\t\t\t\tstrokeColor: getRandomColor(),\r\n");
      out.write("\t\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar color = colorInit[(i+2)%colorInit.length];\r\n");
      out.write("\t\t\tvar lineSymbol = {\r\n");
      out.write("\t\t\t\tpath: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,\r\n");
      out.write("\t\t\t\tstrokeOpacity: 2,\r\n");
      out.write("\t\t\t    scale:1.5\t\t\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\troute = new google.maps.Polyline({\r\n");
      out.write("\t\t\t\tstrokeColor: color,\r\n");
      out.write("\t\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t\t    icons: [{icon: lineSymbol,\r\n");
      out.write("\t\t            offset: '100%',\r\n");
      out.write("\t\t            repeat:'200px'}]\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tvar labelIndex=0;\r\n");
      out.write("\t\troute.getPath().push(storePos);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar checkedListIndex=checkedList[i]\r\n");
      out.write("\t\tfor(var j=0; j<data[checkedListIndex].routeElement.length; j++){\r\n");
      out.write("\t\t\tvar lat = data[checkedListIndex].routeElement[j].addLat;\r\n");
      out.write("\t\t\tvar lng = data[checkedListIndex].routeElement[j].addLng;\r\n");
      out.write("\t\t\tvar point = new google.maps.LatLng(lat,lng);\r\n");
      out.write("\t\t\tvar time = data[checkedListIndex].routeElement[j].expectedTime;\r\n");
      out.write("\t\t\tvar timeEarly = time.substring(0,19);\r\n");
      out.write("\t\t\tvar timeLate = time.substring(20,time.length);\r\n");
      out.write("\t\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t    content: \"STT giao hàng: \"+ data[checkedListIndex].routeElement[j].routeSequence +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Mã khách hàng: \" + data[checkedListIndex].routeElement[j].clientCode +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Địa chỉ: \" + data[checkedListIndex].routeElement[j].clientAddress +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Thời gian giao hàng sớm nhất: \" + timeEarly + \"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Thời gian giao hàng muộn nhất: \" + timeLate + \"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Người giao hàng: \"+ data[checkedListIndex].shipperCode\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tlstinfowindow.push(infowindow);\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition:point,\r\n");
      out.write("\t\t\t\ticon: baseUrl+\"/assets/icon/marker_black16.png\",\r\n");
      out.write("\t\t\t\t//label:labels[labelIndex++ % labels.length],\r\n");
      out.write("\t\t\t\tmap: map,\r\n");
      out.write("\t\t\t\tinfowindow: infowindow\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.addListener('click', function() {\r\n");
      out.write("\t\t\t\tfor(var t=0; t<lstinfowindow.length; t++){\r\n");
      out.write("\t\t\t\t\tlstinfowindow[t].close();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    this.infowindow.open(map, this);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\troute.getPath().push(point);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\troute.setMap(map);\r\n");
      out.write("\t}\r\n");
      out.write("\t//checkedList = [];\r\n");
      out.write("}\r\n");
      out.write("function displayInfo(response){\r\n");
      out.write("\tdata=response;\r\n");
      out.write("\tinitialize();\r\n");
      out.write("\t//var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';\r\n");
      out.write("\t//console.log(\"display response: \"+JSON.stringify(response));\r\n");
      out.write("\tvar storePosition = response[0].storeLatLng;\r\n");
      out.write("\t//console.log(\"storePostion: \"+storePosition);\r\n");
      out.write("\tvar indexPo = storePosition.indexOf(\",\");\r\n");
      out.write("\tvar storePositionLat = storePosition.substring(0,indexPo);\r\n");
      out.write("\t//console.log(\"storePositionLat: \"+storePositionLat);\r\n");
      out.write("\tvar storePositionLng = storePosition.substring(indexPo+1,storePosition.length);\r\n");
      out.write("\t//console.log(\"storePositionLng: \"+storePositionLng);\r\n");
      out.write("\tvar storePos = new google.maps.LatLng(storePositionLat,storePositionLng);\r\n");
      out.write("\tvar markerStorePostion = new google.maps.Marker({\r\n");
      out.write("\t\tposition: storePos,\r\n");
      out.write("\t\ticon : baseUrl+\"/assets/icon/store-icon.png\",\r\n");
      out.write("\t\tmap: map\r\n");
      out.write("\t});\r\n");
      out.write("\tvar lstinfowindow = [];\r\n");
      out.write("\t//var rows = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar colorOfRow = [\"#F9F9F9\",\"#FFFFFF\"];\r\n");
      out.write("\ttable.clear().draw();\r\n");
      out.write("\tfor(var i=0;i<response.length; i++){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//console.log(JSON.stringify(response[i]));\t\t\r\n");
      out.write("\t\tvar route;\r\n");
      out.write("\t\tif(i>=colorInit.length){\r\n");
      out.write("\t\t\troute = new google.maps.Polyline({\r\n");
      out.write("\t\t\t\tstrokeColor: getRandomColor(),\r\n");
      out.write("\t\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar color = colorInit[(i+2)%colorInit.length];\r\n");
      out.write("\t\t\tvar lineSymbol = {\r\n");
      out.write("\t\t\t\tpath: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,\r\n");
      out.write("\t\t\t\tstrokeOpacity: 2,\r\n");
      out.write("\t\t\t    scale:1.5\t\t\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\troute = new google.maps.Polyline({\r\n");
      out.write("\t\t\t\tstrokeColor: color,\r\n");
      out.write("\t\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t\t    icons: [{icon: lineSymbol,\r\n");
      out.write("\t\t            offset: '100%',\r\n");
      out.write("\t\t            repeat:'200px'}]\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar labelIndex=0;\r\n");
      out.write("\t\troute.getPath().push(storePos);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rowColor = colorOfRow[i%2];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//$(firstRowNode).css('background-color',rowColor);\r\n");
      out.write("\t\tfor(var j=0; j<response[i].routeElement.length; j++){\r\n");
      out.write("\t\t\tvar lat = response[i].routeElement[j].addLat;\r\n");
      out.write("\t\t\tvar lng = response[i].routeElement[j].addLng;\r\n");
      out.write("\t\t\tvar point = new google.maps.LatLng(lat,lng);\r\n");
      out.write("\t\t\tvar time = response[i].routeElement[j].expectedTime;\r\n");
      out.write("\t\t\tvar timeEarly = time.substring(0,19);\r\n");
      out.write("\t\t\tvar timeLate = time.substring(20,time.length);\r\n");
      out.write("\t\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t    content: \"STT giao hàng: \"+ response[i].routeElement[j].routeSequence +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Mã khách hàng: \" + response[i].routeElement[j].clientCode +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Địa chỉ: \" + response[i].routeElement[j].clientAddress +\"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Thời gian giao hàng sớm nhất: \" + timeEarly + \"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Thời gian giao hàng muộn nhất: \" + timeLate + \"</br>\"+\r\n");
      out.write("\t\t\t    \t\t\"Người giao hàng: \"+ response[i].shipperCode\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tlstinfowindow.push(infowindow);\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition:point,\r\n");
      out.write("\t\t\t\ticon: baseUrl+\"/assets/icon/marker_black16.png\",\r\n");
      out.write("\t\t\t\t//label:labels[labelIndex++ % labels.length],\r\n");
      out.write("\t\t\t\tmap: map,\r\n");
      out.write("\t\t\t\tinfowindow: infowindow\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.addListener('click', function() {\r\n");
      out.write("\t\t\t\tfor(var t=0; t<lstinfowindow.length; t++){\r\n");
      out.write("\t\t\t\t\tlstinfowindow[t].close();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    this.infowindow.open(map, this);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\troute.getPath().push(point);\r\n");
      out.write("\t\t\tif(j==0){\r\n");
      out.write("\t\t\t\tvar rowNode = table.row.add([\r\n");
      out.write("\t\t\t\t\tresponse[i].routeElement[j].clientCode,\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].clientAddress,\r\n");
      out.write("\t\t\t\t    \"\",\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].expectedTime,\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].routeSequence,\r\n");
      out.write("\t\t\t\t    response[i].shipperCode,\r\n");
      out.write("\t\t\t\t    \"<input type='checkbox' onchange='updateCheckList(\"+i+\", this)'>\"\r\n");
      out.write("\t\t\t\t]).draw().node();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar rowNode = table.row.add([\r\n");
      out.write("\t\t\t\t\tresponse[i].routeElement[j].clientCode,\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].clientAddress,\r\n");
      out.write("\t\t\t\t    \"\",\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].expectedTime,\r\n");
      out.write("\t\t\t\t    response[i].routeElement[j].routeSequence,\r\n");
      out.write("\t\t\t\t    response[i].shipperCode,\r\n");
      out.write("\t\t\t\t    \"\"\r\n");
      out.write("\t\t\t\t]).draw().node();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//var rowColor = colorOfRow[i%2];\r\n");
      out.write("\t\t\t$(rowNode).css('background-color',rowColor);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t//table.row.add([\r\n");
      out.write("\t\t\trows += \"<tr style='background-color:\"+colorOfRow[i%2]+\"'>\";\r\n");
      out.write("\t\t\trows += \"<td>\" + response[i].routeElement[j].clientCode +\"</td>\"\r\n");
      out.write("\t\t\trows += \"<td>\" + response[i].routeElement[j].clientAddress + \"</td>\";\r\n");
      out.write("\t\t\trows += \"<td></td>\"; \r\n");
      out.write("\t\t\trows += \"<td>\"+response[i].routeElement[j].expectedTime+\"</td>\";\r\n");
      out.write("\t\t\trows += \"<td>\"+response[i].routeElement[j].routeSequence+\"</td>\";\r\n");
      out.write("\t\t\trows += \"<td>\"+response[i].shipperCode+\"</td>\";\r\n");
      out.write("\t\t\trows += \"</tr>\";\r\n");
      out.write("\t\t\t//]).draw( false );*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\troute.setMap(map);\r\n");
      out.write("\t}\r\n");
      out.write("\t//$(\"table#tbl-infoOfRoutes tbody\").append(rows);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getRandomColor() {\r\n");
      out.write("    var letters = '0123456789ABCDEF';\r\n");
      out.write("    var color = '#FF';\r\n");
      out.write("    for (var i = 0; i < 4; i++ ) {\r\n");
      out.write("        color += letters[Math.floor(Math.random() * 10)];\r\n");
      out.write("    }\r\n");
      out.write("    return color;\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(6,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/assets/libs/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(9,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/assets/libs/datatables-responsive/css/dataTables.responsive.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(22,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(22,5) '${lstBatch}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${lstBatch}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(22,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("batch");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${batch.REQBAT_Code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(23,43) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${batch.REQBAT_Description}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(39,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(39,7) '${lstShipper}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${lstShipper}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(39,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("shipper");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipper.SHP_Code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(40,44) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipper.SHP_Code }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(75,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/assets/libs/datatables/media/js/jquery.dataTables.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/views/outgoingarticles/viewAutoRoute.jsp(76,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/assets/libs/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }
}
