/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2017-08-09 16:07:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.dichung;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewRouteDiChung_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar", Long.valueOf(1423481836151L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1386784424000L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1386784424000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1423481802197L));
    _jspx_dependants.put("jar:file:/C:/DungPQ/research/projects/cblsvr/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/slp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"> </script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"> </script>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("\t<div class=\"form-group \">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" >Chọn Lô</label>\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<select class=\"form-control batchselect\" onchange=\"loadRoute()\"  >\r\n");
      out.write("\t\t\t\t<option value=\"\">Chọn Lô</option>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("         </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<h1 class=\"page-header\">Chi tiết các tuyến</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-12 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"\"><b> Bộ lọc  </b> </h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-1\">Ngày</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input  class=\"form-control datepicker \" name=\"dateFilter\" onchange=\"updateFilter()\" placeholder=\"Date\" ></input>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-lg-1\">Từ:</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input   class=\"form-control timepicker\" id=\"timeearly\" onchange=\"updateFilter()\" placeholder=\"TimeEarly\" ></input>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-1\">Đến:</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input   class=\"form-control timepicker\" id=\"timelate\"  onchange=\"updateFilter()\" placeholder=\"TimeLate\" ></input>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"map\" style=\"height:100%\">\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-lg-1\">Chọn Shipper</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"shipperselect\" name=\"shipperselect\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"form-group btn btn-primary active\" title=\"\" onclick=\"assignShipper()\">Assign Shipper</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"  class=\"form-group btn btn-primary active\" title=\"\" onclick=\"viewRoute()\">View Routes</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dataTable_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover\" id=\"tableRoute\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>TicketCode</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>DeliveryAddress</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>PickupDateTime</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Sequence </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Shipper</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Check</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--/.dataTable_wrapper -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.panel-body -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.panel -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-12 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /#page-wrapper -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var checkedList=[];\r\n");
      out.write("var indexRowTable=[];\r\n");
      out.write("var pathList=[];// danh sach cac poliline\r\n");
      out.write("var markerList=[]; // danh sach cac marker\r\n");
      out.write("var sortListData=[]; //danh sach index data sorted\r\n");
      out.write("var colorInit=[\"#F7786B\",\"#91A8D0\",\"#91A8D0\",\"#034F84\",\"#FAE03C\",\"#98DDDE\",\"#9896A4\",\"#DD4132\",\"#B18F6A\",\"#79C753\",\"#B93A32\",\"#AD5D5D\",\"#006E51\",\"#B76BA3\",\"#5C7148\",\"#D13076\"]; // mang init mau\r\n");
      out.write("var table;\r\n");
      out.write("var data;\r\n");
      out.write("$('.timepicker').timepicker({\r\n");
      out.write("\tshowMeridian: false \r\n");
      out.write("});\r\n");
      out.write("$(function() {\r\n");
      out.write("    $( \".datepicker\" ).datepicker({\r\n");
      out.write("    \tformat:\"yyyy-mm-dd\"\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("function initMap() {\r\n");
      out.write("\tdirectionsService = new google.maps.DirectionsService;\r\n");
      out.write("\tserviceDistance = new google.maps.DistanceMatrixService;\r\n");
      out.write("    var mapDiv = document.getElementById('map');\r\n");
      out.write("    map = new google.maps.Map(mapDiv, {\r\n");
      out.write("        center: {lat: 21.03, lng: 105.8},\r\n");
      out.write("        zoom: 13\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\ttable=$(\"#tableRoute\").DataTable({\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("function loadRoute(){\r\n");
      out.write("\tvar batchCode= $(\".batchselect\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t    type:\"POST\", \r\n");
      out.write("\t    url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dichung/load-route-in-batch\",\r\n");
      out.write("\t    data: batchCode,\r\n");
      out.write("\t    contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t    dataType: \"json\",\r\n");
      out.write("\t    success: function(response){\r\n");
      out.write("\t        // Success Message Handler\r\n");
      out.write("\t        //console.log(response);\r\n");
      out.write("\t        data=response;\r\n");
      out.write("\t        init(data);\r\n");
      out.write("\t        loadTable(response);\r\n");
      out.write("\t        viewMap(response);\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function pushMomentObject(){\r\n");
      out.write("\tfor(var i=0;i<data.length;i++)\r\n");
      out.write("\t\tfor(var j=0;j<data[i].listPoint.length;j++){\r\n");
      out.write("\t\tdata[i].listPoint[j].momentObject=\tmoment(data[i].listPoint[j].rddc_PickupDateTime,\"YYYY-MM-DD HH:mm:ss\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function randomColor(){\r\n");
      out.write("/*\tp1=Math.floor((Math.random() * 85));\r\n");
      out.write("\tp2=Math.floor((Math.random() * 255));\r\n");
      out.write("\tp3=Math.floor((Math.random() * 255));\r\n");
      out.write("\treturn \"rgb(\"+p1+\",\"+p2+\",\"+p3+ \")\";*/\r\n");
      out.write("\treturn colorInit[Math.floor((Math.random() * colorInit.length))];\r\n");
      out.write("}\r\n");
      out.write("function viewMap(data){\r\n");
      out.write("\t\r\n");
      out.write("\tvar route;\r\n");
      out.write("\t\r\n");
      out.write("\tvar xd=false;\r\n");
      out.write("\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t//console.log(i);\r\n");
      out.write("\t\t//console.log(JSON.stringify(response[i]));\r\n");
      out.write("\t\tvar list= data[i].listPoint;\r\n");
      out.write("\t\tif(list.length>=2){\r\n");
      out.write("\t\troute = new google.maps.Polyline({\r\n");
      out.write("\t\t\tstrokeColor: randomColor(),\r\n");
      out.write("\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tpathList.push(route);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var j=0;j<list.length;j++){\r\n");
      out.write("\t\t\tvar latlng=list[j].rddc_LatLng;\r\n");
      out.write("\t\t\tvar lat = latlng.substring(0,latlng.indexOf(',')) ;\r\n");
      out.write("\t\t\tvar lng = latlng.substring(latlng.indexOf(',')+1,latlng.length) ;\r\n");
      out.write("\t\t\tvar point = new google.maps.LatLng(lat,lng);\r\n");
      out.write("\t\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t    content: \"Pickup Address: \"+ list[j].rddc_Address +\"<br> Delivery Address: \" + list[j].rddc_DeliveryAddress+\"<br> Pickup Date Time:\"+list[j].rddc_PickupDateTime\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition:point,\r\n");
      out.write("\t\t\t\tmap: map,\r\n");
      out.write("\t\t\t\tlabel:null,\r\n");
      out.write("\t\t\t\ticon: baseUrl+\"/assets/icon/oval_green.png\",\r\n");
      out.write("\t\t\t\tpath: pathList.indexOf(route),\r\n");
      out.write("\t\t\t\tinfowindow: infowindow\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.addListener('click', function() {\r\n");
      out.write("\t\t\t    this.infowindow.open(map, this);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tlist[j].marker=marker;\r\n");
      out.write("\t\t\tmarkerList.push(marker);\r\n");
      out.write("\t\t\troute.getPath().push(point);\r\n");
      out.write("\t\t\troute.setMap(map);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\tvar latlng=list[0].rddc_LatLng;\r\n");
      out.write("\t\t\tvar lat = latlng.substring(0,latlng.indexOf(',')) ;\r\n");
      out.write("\t\t\tvar lng = latlng.substring(latlng.indexOf(',')+1,latlng.length) ;\r\n");
      out.write("\t\t\tvar point = new google.maps.LatLng(lat,lng);\r\n");
      out.write("\t\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t    content: \"Pickup Address: \"+ list[0].rddc_Address +\"<br> Delivery Address: \" + list[0].rddc_DeliveryAddress+\"<br> Pickup Date Time:\"+list[0].rddc_PickupDateTime\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\tposition:point,\r\n");
      out.write("\t\t\t\tmap: map,\r\n");
      out.write("\t\t\t\tlabel:null,\r\n");
      out.write("\t\t\t\ticon: baseUrl+\"/assets/icon/oval_blue.png\",\r\n");
      out.write("\t\t\t\tpath: -1,\r\n");
      out.write("\t\t\t\tinfowindow: infowindow\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.addListener('click', function() {\r\n");
      out.write("\t\t\t    this.infowindow.open(map, this);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tdata[i].listPoint[0].marker=marker;\r\n");
      out.write("\t\t\tmarkerList.push(marker);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function sortList(data){ // thua\r\n");
      out.write("\tfor(var i=0;i<data.length;i++)\r\n");
      out.write("\t\tsortListData[i]=i;\r\n");
      out.write("\tfor(var i=0;i<data.length-1;i++){\r\n");
      out.write("\t\tfor(var j=i+1;j<data.length;j++){\r\n");
      out.write("\t\t\tif(data[sortListData[i]].momentObject.isAfter(data[sortListData[j]].momentObject)){\r\n");
      out.write("\t\t\t\tvar tmp=sortListData[i];\r\n");
      out.write("\t\t\t\tsortListData[i]=sortListData[j];\r\n");
      out.write("\t\t\t\tsortListData[j]=tmp;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateFilter(){\r\n");
      out.write("\tvar dateFilter=$(\".datePicker\").val();\r\n");
      out.write("\ttimeearly=$(\"#timeearly\").val();\r\n");
      out.write("\ttimelate=$(\"#timelate\").val();\r\n");
      out.write("\ttimeearly=moment(timeearly,\"HH:mm\");\r\n");
      out.write("\ttimelate=moment(timelate,\"HH:mm\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar dateTimeFilterEarly=moment(dateFilter,\"YYYY-MM-DD\");\r\n");
      out.write("\tvar dateTimeFilterLate=moment(dateFilter,\"YYYY-MM-DD\");\r\n");
      out.write("\tdateTimeFilterEarly=moment(dateTimeFilterEarly.format('YYYY-MM-DD ')+ timeearly.format(\"HH:mm\"),\"YYYY-MM-DD HH:mm:ss\");\r\n");
      out.write("\tdateTimeFilterLate=moment(dateTimeFilterLate.format('YYYY-MM-DD ')+ timelate.format(\"HH:mm\"),\"YYYY-MM-DD HH:mm:ss\");\r\n");
      out.write("\tif(pathList!=null)\r\n");
      out.write("\tfor(var i=0;i<pathList.length;i++)\r\n");
      out.write("\t\tpathList[i].setMap(null);\r\n");
      out.write("\tif(data!=null)\r\n");
      out.write("\tfor(var i=0;i<data.length;i++ ){\r\n");
      out.write("\t\tvar list=data[i].listPoint;\r\n");
      out.write("\t\tfor(var j=0;j<list.length;j++){\r\n");
      out.write("\t\tif(list[j].momentObject.isSameOrAfter(dateTimeFilterEarly) && list[j].momentObject.isSameOrBefore(dateTimeFilterLate)){\r\n");
      out.write("\t\t\tlist[j].marker.setMap(map);\r\n");
      out.write("\t\t\tif(list[j].marker.path!=-1)\r\n");
      out.write("\t\t\t\tpathList[list[j].marker.path].setMap(map);\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\tlist[j].marker.setMap(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function viewRoute(){\r\n");
      out.write("\tfor(var i=0;i<pathList.length;i++)\r\n");
      out.write("\t\tpathList[i].setMap(null);\r\n");
      out.write("\tfor(var i=0;i<markerList.length;i++ )\r\n");
      out.write("\t\tmarkerList[i].setMap(null);\r\n");
      out.write("\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t\tlist=data[checkedList[i]].listPoint;\r\n");
      out.write("\t\tfor(var j=0;j<list.length;j++){\r\n");
      out.write("\t\t\tlist[j].marker.setMap(map);\r\n");
      out.write("\t\t\tif(list[j].marker.path!=-1)\r\n");
      out.write("\t\t\t\tpathList[list[j].marker.path].setMap(map);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("function assignShipper(){\r\n");
      out.write("\tvar shipper= $(\"#shipperselect\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tres={\r\n");
      out.write("\t\t\"shipper\":shipper\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tres[\"listRoute\"]=[];\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t\tres.listRoute.push(data[checkedList[i]].route_Code);\r\n");
      out.write("\t}\r\n");
      out.write("\tconsole.log(res);\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t    type:\"POST\", \r\n");
      out.write("\t    url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ship/update-route-assignshipper\",\r\n");
      out.write("\t    data: JSON.stringify(res),\r\n");
      out.write("\t    contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t    dataType: \"json\",\r\n");
      out.write("\t    success: function(response){\r\n");
      out.write("\t        // Success Message Handler\r\n");
      out.write("\t        //console.log(response);\r\n");
      out.write("\t      \tif(response==true){\r\n");
      out.write("\t      \t\tfor(var i=0;i<checkedList.length;i++){\r\n");
      out.write("\t      \t\t\tfor(var j=0;j<data[checkedList[i]].listPoint.length;j++){\r\n");
      out.write("\t      \t\t\t\tvar cells=document.getElementById(\"tableRoute\").rows[indexRowTable[checkedList[i]]+1+j].cells;\r\n");
      out.write("\t      \t\t\t\tcells[5].innerHTML=shipper;\r\n");
      out.write("\t      \t\t\t}\r\n");
      out.write("\t      \t\t}\r\n");
      out.write("\t      \t\t\r\n");
      out.write("\t      \t}\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function loadTable(data){\r\n");
      out.write("\t//console.log(data);\r\n");
      out.write("\t$(\"table#tableRoute tbody\").html(\"\");\r\n");
      out.write("\tgray=\"#F0F0F0\";\r\n");
      out.write("\twhite=\"#FFFFFF\";\r\n");
      out.write("\tvar color=[\"#F0F0F0\",\"#FFFFFF\"];\r\n");
      out.write("\tvar idcolor=0;\r\n");
      out.write("\tstr=null;\r\n");
      out.write("\tcount=0;\r\n");
      out.write("\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t//console.log(\"i data[i].rddc_Group\" +data[i].rddc_Group); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tidcolor=(idcolor+1) % color.length;\r\n");
      out.write("\t\t\t//console.log(\"id\"+idcolor);\r\n");
      out.write("\t\t\t//console.log(\"length \"+ color.length+\" \"+idcolor % color.length);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar list=data[i].listPoint;\r\n");
      out.write("\t\tindexRowTable[i]=count;\r\n");
      out.write("\t\tfor(var j=0;j<list.length;j++){\r\n");
      out.write("\t\t\tstr+=\"<tr\"+\" style='background-color:\"+color[idcolor]+\"' \"+\">\";\r\n");
      out.write("\t\t\tstr+=\"<td>\"+list[j].rddc_TicketCode+\"</td>\"\r\n");
      out.write("\t\t\tstr+=\"<td>\"+list[j].rddc_Address+\"</td>\"\r\n");
      out.write("\t\t\tstr+=\"<td>\"+list[j].rddc_DeliveryAddress+\"</td>\"\r\n");
      out.write("\t\t\tstr+=\"<td>\"+list[j].rddc_PickupDateTime+\"</td>\"\r\n");
      out.write("\t\t\tstr+=\"<td>\"+list[j].rddc_Sequence+\"</td>\"\r\n");
      out.write("\t\t\tstr+=\"<td>\"+data[i].route_Shipper_Code+\"</td>\";\r\n");
      out.write("\t\t\tif(j==0)\r\n");
      out.write("\t\t\t\tstr+=\"<td>\"+\"<div class='checkbox'> <label><input type='checkbox' onchange=updateCheckList(\"+i+\") value=''></label></div>\"+\"</td>\";\r\n");
      out.write("\t\t\t\telse str+=\"<td>\"+\"</td>\";\r\n");
      out.write("\t\t\tstr+=\"</tr>\"\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"table#tableRoute tbody\").append(str);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateCheckList(i){\r\n");
      out.write("\tvar tmp= checkedList.indexOf(i);\r\n");
      out.write("\t\r\n");
      out.write("\tif (tmp==-1) checkedList.push(i);\r\n");
      out.write("\telse checkedList.splice(tmp,1);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function init(data){\r\n");
      out.write("\tpathList=[];\r\n");
      out.write("\tmarkerList=[];\r\n");
      out.write("\tsortListData=[]; \r\n");
      out.write("\tpushMomentObject();\r\n");
      out.write("\t//sortList(data);\r\n");
      out.write("\t//console.log(data);\r\n");
      out.write("}\r\n");
      out.write("function pushNewFilterTime(timeEarly, timeLate){\r\n");
      out.write("\t//console.log(timeEarly+\" \"+timeLate);\r\n");
      out.write("\t$(\"#timeearly\").html(timeEarly);\r\n");
      out.write("\t$(\"#timelate\").html(timeLate);\r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("<script async defer\r\n");
      out.write("        src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDEXgYFE4flSYrNfeA7VKljWB_IhrDwxL4&callback=initMap\">\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(5,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/assets/libs/datatables/media/js/jquery.dataTables.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(6,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/assets/libs/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(7,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/assets/libs/jquery-ui-1.12.0/jquery-ui.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(8,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/assets/libs/bootstrap-slider/bootstrap-slider.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(9,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/assets/libs/bootstrap-slider/css/bootstrap-slider.css");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(10,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/assets/libs/bootstrap-timepicker/css/bootstrap-timepicker.css");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(11,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.css");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f7.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(12,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f7.setValue("/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.js");
    int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
    if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f8.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(13,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f8.setValue("/assets/libs/inputDate/dist/js/moment.js");
    int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
    if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f9.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(14,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f9.setValue("/assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.js");
    int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
    if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(22,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dichung/viewRouteDiChung.jsp(22,4) '${listBatch}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${listBatch}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(22,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("lbatch");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lbatch.REQBAT_Code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lbatch.REQBAT_Code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(70,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dichung/viewRouteDiChung.jsp(70,7) '${listShipper}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${listShipper}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(70,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("shippers");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shippers.SHP_Code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/dichung/viewRouteDiChung.jsp(71,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shippers.SHP_Code}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
